FoundationDB/sql-layer

fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/routines/ScriptCache.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/server/ServerJavaRoutine.java
fdb-sql-layer-test-yaml/src/test/resources/com/foundationdb/sql/test/yaml/functional/test-routine-transactions.yaml

Call of nested routines was not possible, as the permissions to get and set the context class loader were not available inside a routine.

Call of nested routines

---

fdb-sql-layer-core/src/main/java/com/foundationdb/ais/model/AISBuilder.java
fdb-sql-layer-core/src/main/java/com/foundationdb/ais/model/AISMerge.java
fdb-sql-layer-core/src/main/java/com/foundationdb/ais/model/DefaultNameGenerator.java
fdb-sql-layer-core/src/main/java/com/foundationdb/ais/model/ForeignKey.java
fdb-sql-layer-core/src/main/java/com/foundationdb/ais/model/Index.java
fdb-sql-layer-core/src/main/java/com/foundationdb/ais/model/validation/ForeignKeyIndexes.java
fdb-sql-layer-core/src/main/java/com/foundationdb/qp/storeadapter/indexrow/FDBIndexRow.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/error/ForeignKeyIndexRequiredException.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/dxl/BasicDDLFunctions.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/is/BasicInfoSchemaTablesServiceImpl.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/aisddl/AlterTableDDL.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/aisddl/TableDDL.java
fdb-sql-layer-core/src/main/resources/com/foundationdb/server/error/error_code.properties
fdb-sql-layer-core/src/test/java/com/foundationdb/server/service/is/BasicInfoSchemaTablesServiceImplTest.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/test/it/dxl/CreateIndexesIT.java
fdb-sql-layer-core/src/test/java/com/foundationdb/sql/aisddl/AlterTableDDLTest.java
fdb-sql-layer-core/src/test/resources/com/foundationdb/sql/optimizer/rule/pick-fk-joins/join-fk-4.expected
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresEmulatedMetaDataStatement.java
fdb-sql-layer-test-yaml/src/test/resources/com/foundationdb/sql/test/yaml/functional/test-foreign-key-ddl.yaml

If possible. If not, create and index as before but also ensure it has a unique name.
This avoids creating redundant indexes (e.g. join-fk-4.expected) and avoids an error when the DDL already contains an index of the same name (e.g. migration).
This is implicitly compatible with previously created schemas as the index is looked up at AIS load time, just like referenced side indexes.
Note that now that there is no longer a 1-1 mapping any index that was implicitly created is no longer dropped if the FK is dropped. We could mark such indexes but that keeping them actually seems pretty reasonable from a query plan predictability standpoint.

Use existing index for referencing side of FOREIGN KEY

---

fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/is/ServerSchemaTablesServiceImpl.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/monitor/MonitorService.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/monitor/MonitorServiceImpl.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/monitor/SessionEventListener.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/monitor/SessionMonitor.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/monitor/SessionMonitorBase.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/service/is/ServerSchemaTablesServiceIT.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresBaseCursorStatement.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresCopyInStatement.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresCopyOutStatement.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresDDLStatement.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresEmulatedMetaDataStatement.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresEmulatedSessionStatement.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresExplainStatement.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresJavaRoutine.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresModifyOperatorStatement.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresOperatorStatement.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresServerConnection.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresServerStatement.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresSessionStatement.java

This merge does two things. 
It add a collection of counter to the SessionMonitor for counting the types of statements being run through the Postgres Interface. The counters enhance the "Statements" count with Failed, From Cache, and Logged statments, plus a count of the different types of statements : Select, DML, DDL, call, copy, explain, emulated metadata, alter session, and alter server calls. These statistics are exposed through additional columns to the IS.SERVER_SESSIONS table.
Second it makes the MonitorService also collect the same set of statistics from all the sessions. These are exposed through a new IS.SERVER_STATISTICS_SUMMARY table.

Monitor service monitor more stats

---

fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresServer.java
fdb-sql-layer-rest/src/main/java/com/foundationdb/http/HttpConductorImpl.java

Postgres was delaying figuring out what authentication to use from config properties until the first connect, which doesn't seem important.
Also clarify in a comment what a nearby authentication-related method is doing.

Make network server startup messages parallel.

---

fdb-sql-layer-rest/pom.xml

There is a task to upgrade to 9, but that requires some changes on our end.
Also add jetty-plus, which has modules that customer may want to configure with some upcoming changes.
The purpose of having this as a separate PR is just to see whether anything breaks.

Update Jetty dependency to latest in 8.1 stream

---

fdb-sql-layer-core/src/main/java/com/foundationdb/ais/model/Constraint.java
fdb-sql-layer-core/src/main/java/com/foundationdb/ais/model/ForeignKey.java
fdb-sql-layer-core/src/main/java/com/foundationdb/ais/model/Index.java
fdb-sql-layer-core/src/main/java/com/foundationdb/ais/model/Join.java
fdb-sql-layer-core/src/main/java/com/foundationdb/ais/model/TableIndex.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/aisddl/AlterTableDDL.java
fdb-sql-layer-core/src/test/java/com/foundationdb/sql/aisddl/AlterTableDDLTest.java
fdb-sql-layer-test-yaml/src/test/resources/com/foundationdb/sql/test/yaml/functional/test-alter-drop-constraint-long-identifier.yaml

The alter code was still looking index names to figure out which constraint to drop. That isn't correct now that we have real constraint names and could fail when ones that often match didn't.

Fix constraint dropping

---

fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/security/SecurityService.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/security/SecurityServiceImpl.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/embedded/EmbeddedJDBCService.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/embedded/EmbeddedJDBCServiceImpl.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/service/security/DummySecurityService.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/service/security/SecurityServiceITBase.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresServer.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresServerConnection.java
fdb-sql-layer-rest/src/main/java/com/foundationdb/http/HttpConductorImpl.java
fdb-sql-layer-rest/src/main/java/com/foundationdb/http/HybridLoginService.java
fdb-sql-layer-rest/src/main/java/com/foundationdb/rest/dml/RestDMLServiceImpl.java

@nathanlws convinced me that doing this via JAAS was the best, if not the simplest, way.
As with Kerberos, the JAAS configuration file must be configured in `jvm.options`. A `fdbsql.{sql,postgres,http}.jaas.configName` config setting names the login module to use. Unlike with GSS, this module logs the client in, not the server. See https://bitbucket.org/mmcm/sql-layer-docker/src/470ddfb7a583d3a57a893cd05592fa2ab4a663b5/ldap-sql-layer/jaas.conf?at=master for examples.
If `...jaas.roleClasses` is defined, it names `Principal` classes that are taken from the `Subject` and assumed to have names that map directly to roles in the SQL layer. In short, roles come from directory. If this is not defined, roles come from the security database, matching the name of the user `Principal` after …

Support LDAP authentication

---

fdb-sql-layer-core/src/main/java/com/foundationdb/sql/embedded/JDBCConnection.java
fdb-sql-layer-test-yaml/src/test/resources/com/foundationdb/sql/test/yaml/bugs/test-embedded-jdbc-schema.yaml

Using the "database" property. If none is supplied, it moves in the other direction, as before (as of relatively recently).

Opening embedded JDBC driver is allowed to overwrite the inherited schema

---

fdb-sql-layer-rest/src/main/java/com/foundationdb/http/HttpConductorImpl.java
fdb-sql-layer-rest/src/main/java/com/foundationdb/http/HybridLoginService.java
fdb-sql-layer-rest/src/main/java/com/foundationdb/http/SpnegoAuthenticatorEx.java

All the work is done by two Jetty classes, which are further initialized via a Properties file (only way) taken from a subset of the config database.
It would be perfectly reasonable to wait until the Docker example is checked in before believing that it is possible to put in settings that work.

Add REST login option spnego for Kerberos authentication using GSSAPI

---

fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/monitor/MonitorService.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/monitor/MonitorServiceImpl.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/monitor/SessionMonitorBase.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/embedded/JDBCConnection.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/embedded/JDBCStatement.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresServerConnection.java

Previously only the timeout-related ones (e.g. `not_committed`) were logged.
Include error message in such an entry. Otherwise row count processed.
Also log from embedded driver more consistently.

Log errors in query log if they meet the time constraint or are timeout-related

---

fdb-sql-layer-core/src/main/java/com/foundationdb/sql/server/ServerSessionBase.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresSessionStatement.java

I appreciate that such support is a slippery-slope. But there is no way to keep recent Npgsql from sending this and the translation is straightforward.

Convert Postgres-compatible statement_timeout to queryTimeoutMillis.

---

fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/TClassBase.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/TExecutionContext.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/common/funcs/Base64.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/common/funcs/DescribeExpression.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/common/funcs/DistanceLatLon.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/common/funcs/GeoLatLon.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/common/funcs/Hex.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/common/funcs/NullIf.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/common/types/TBigDecimal.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/common/types/TBinary.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/mcompat/mcasts/Cast_From_Boolean.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/mcompat/mcasts/Cast_From_Decimal.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/mcompat/mfuncs/MAbs.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/mcompat/mfuncs/MArithmetic.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/mcompat/mfuncs/MAscii.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/mcompat/mfuncs/MDateAddSub.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/mcompat/mfuncs/MField.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/mcompat/mfuncs/MLength.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/mcompat/mfuncs/MRoundBase.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/mcompat/mfuncs/MRoundTruncateDecimal.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/mcompat/mfuncs/MSign.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/mcompat/mfuncs/MUnaryMinus.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/service/TCastsRegistry.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/texpressions/TInExpression.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/texpressions/TScalarBase.java

TScalarBase had to change to a little, but the input types should be correct now and inputTypeAt shouldn't be necessary.

Get rid of TExecutionContext#inputTypeAt

---

fdb-sql-layer-core/src/main/java/com/foundationdb/server/store/FDBStore.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/store/FDBStoreIT.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/test/it/FDBITBase.java

Otherwise they Sequence (and AIS and ...) get leaked.

Maintain sequence cache when dropping schemas

---

fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/TClass.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/mcompat/mtypes/MNumeric.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/types/AkTypesComparisonTest.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/types/MTypesComparisonTest.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/types/TypeComparisonTestBase.java

For integer, use stock compare() as subtraction can wrap around and give the wrong answer. Override and use proper method for `bigint unsigned` as well.

Fix TClass#doCompare integer handling

---

fdb-sql-layer-core/src/main/java/com/foundationdb/server/error/NotAllowedByConfigException.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/error/StartupFailureException.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/dxl/BasicDDLFunctions.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/store/AbstractSchemaManager.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/store/FDBSchemaManager.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/store/SchemaManager.java
fdb-sql-layer-core/src/main/resources/com/foundationdb/server/service/config/configuration-defaults.properties
fdb-sql-layer-core/src/test/java/com/foundationdb/server/service/config/TestConfigService.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/service/is/BasicInfoSchemaTablesServiceImplTest.java

Due to Tuple ordering issue, as discussed.
Handled as a "feature" config option so anyone affected can at least be walked through recovery.

Reject indexes on BOOLEAN by default

---

fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/config/ConfigurationServiceImpl.java

Needed, I think, if we want to keep hassle-free RHEL/CentOS 6 support.

Reduce invalid user.timezone to log error message

---

fdb-sql-layer-core/src/main/java/com/foundationdb/sql/server/ServerValueDecoder.java

As they are exercised by ODBC.

Restore support for binary string parameters.

---

fdb-sql-layer-test-yaml/src/test/resources/com/foundationdb/sql/test/yaml/functional/test-bug-null-in-FK.yaml
fdb-sql-layer-test-yaml/src/test/resources/com/foundationdb/sql/test/yaml/functional/test-unions-with-null.yaml

The test-unions-with-null test needs to skip the prepared statement section of the test, which fortunately is at the end of the test.
The test-bug-with-null-in-FK test needed to do the two rows of insert in the same statement to avoid having the sequence on two servers insert data that's not expected.

Fix fts random failing tests

---

fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/statusmonitor/StatusMonitorServiceImpl.java

to allow IT (and presumably everything else) to pass quickly.
Also set name on the thread per trello card request.

Reverse the polarity of the backgroundIdle setting

---

fdb-sql-layer-core/src/main/java/com/foundationdb/server/store/AbstractSchemaManager.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/store/FDBSchemaManager.java
fdb-sql-layer-core/src/main/java/com/foundationdb/tuple/TupleFloatingUtil.java
fdb-sql-layer-core/src/main/resources/com/foundationdb/server/service/config/configuration-defaults.properties
fdb-sql-layer-core/src/test/java/com/foundationdb/server/service/config/TestConfigService.java
fdb-sql-layer-test-yaml/src/test/resources/com/foundationdb/sql/test/yaml/functional/test-sort-boolean.yaml

Also bumps the data version for FDB and removes the old compromise check.

Switch to new true code; give error for former one

---

fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/statusmonitor/StatusMonitorServiceImpl.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/service/statusmonitor/StatusMonitorServiceIT.java

Two changes: 
- change the names with spaces (memory pools, garbage collectors) to use underscores
- Convert the start time columns to unix_timestamp()

Update the StatusMonitor per the request of the Status Monitor team

---

fdb-sql-layer-core/src/main/java/com/foundationdb/qp/storeadapter/indexcursor/ValueSortKeyAdapter.java
fdb-sql-layer-test-yaml/src/test/resources/com/foundationdb/sql/test/yaml/bugs/test-issue-1660.yaml

The issue is that the declared type of the index column may not be the same as the either of the two identival bound values.

Fix consistency checker for index bounds for key-comparables

---

fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/routines/RoutineLoader.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/routines/RoutineLoaderImpl.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/service/routines/ScriptCache.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/embedded/EmbeddedOperatorCompiler.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/embedded/ExecutableJavaMethod.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/embedded/ExecutableJavaRoutine.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/embedded/ExecutableLoadableOperator.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/embedded/ExecutableModifyOperatorStatement.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/embedded/ExecutableOperatorStatement.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/embedded/ExecutableQueryOperatorStatement.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/embedded/ExecutableScriptBindingsRoutine.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/embedded/ExecutableScriptFunctionJavaRoutine.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/embedded/ExecutableStatement.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/embedded/JDBCStatement.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/script/ScriptBindingsRoutineTExpression.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/script/ScriptFunctionJavaRoutineTExpression.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/server/ServerJavaMethodTExpression.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/service/routines/MockRoutineLoader.java
fdb-sql-layer-core/src/test/java/com/foundationdb/sql/embedded/EmbeddedJDBCIT.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresJavaMethod.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresScriptBindingsRoutine.java
fdb-sql-layer-pg/src/main/java/com/foundationdb/sql/pg/PostgresScriptFunctionJavaRoutine.java

And give an error if one is used after it changes.
Mostly plumbing to get the AIS generation down to the statements.

Track AIS generation in embedded JDBC prepared statements

---

fdb-sql-layer-core/src/main/java/com/foundationdb/sql/optimizer/rule/PlanGenerator.java

Make PlanGenerator#generateIndexScan() use ascending order for index scans

---

fdb-sql-layer-core/src/main/java/com/foundationdb/qp/expression/IndexBound.java
fdb-sql-layer-core/src/main/java/com/foundationdb/qp/expression/RowBasedUnboundExpressions.java
fdb-sql-layer-core/src/main/java/com/foundationdb/qp/expression/UnboundExpressions.java
fdb-sql-layer-core/src/main/java/com/foundationdb/qp/operator/RowCursorImpl.java
fdb-sql-layer-core/src/main/java/com/foundationdb/qp/storeadapter/FDBGroupCursor.java
fdb-sql-layer-core/src/main/java/com/foundationdb/qp/storeadapter/indexcursor/IndexCursorUnidirectional.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/store/FDBStore.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/texpressions/SubqueryTExpression.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/texpressions/TCastExpression.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/texpressions/TComparisonExpressionBase.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/texpressions/TNullExpression.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/texpressions/TPreparedBoundField.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/texpressions/TPreparedExpression.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/texpressions/TPreparedField.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/texpressions/TPreparedFunction.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/texpressions/TPreparedLiteral.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/texpressions/TPreparedParameter.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/texpressions/TSequenceNextValueExpression.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/texpressions/TValidatedScalar.java
fdb-sql-layer-core/src/main/java/com/foundationdb/sql/server/ServerJavaRoutineTExpression.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/test/ExpressionGenerators.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/test/it/qp/IndexScanBoundedIT.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/test/it/qp/UniqueIndexScanIT.java
fdb-sql-layer-test-yaml/src/test/resources/com/foundationdb/sql/test/yaml/bugs/test-bug-null-in-indexscan.yaml

Address one more case of using NULL in statements which use an index scan incorrectly. In this case `SELECT * FROM t WHERE x = ?` where the parameter is set to `null` should return no rows, but the query  `SELECT * from t WHERE x IS NULL;` should return rows. In `IndexCursorUnidirectional.java`, there isn't any way to distinguish between these two cases. This branch adds one. 
It checks the underlying implementations of the expressions used for the range on the scan to ensure the source is a literal null or not. If so, the second query is assumed and does the range correctly. If not a literal, the first form is assumed, and the cursor is flagged to not return any rows. 
To make the IndexCursorUnidirectional as aggressive about skipping the processing, including creating the underlying …

Null in index scan checking

---

fdb-sql-layer-core/src/main/java/com/foundationdb/server/rowdata/ConversionHelperBigDecimal.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/common/BigDecimalWrapperImpl.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/common/types/TBigDecimal.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/types/value/ValueSources.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/types/DecimalSelfCastTest.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/types/value/ValueSourcesTest.java

Fixes bug when ValueSources is handed a BigDecimalWrapper with a prec/scale that don't match SQL's view (e.g. 0.01).

Helper for computing precision and scale from BigDecimal

---

fdb-sql-layer-core/src/main/java/com/foundationdb/qp/storeadapter/FDBIterationHelper.java
fdb-sql-layer-core/src/main/java/com/foundationdb/qp/storeadapter/PersistitIterationHelper.java
fdb-sql-layer-core/src/main/java/com/foundationdb/qp/storeadapter/indexcursor/IndexCursorUnidirectional.java
fdb-sql-layer-core/src/main/java/com/foundationdb/qp/storeadapter/indexcursor/IterationHelper.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/store/FDBStore.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/store/FDBStoreData.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/store/format/FDBStorageDescription.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/store/statistics/FDBStoreIndexStatistics.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/test/it/qp/Except_OrderedIT.java
fdb-sql-layer-core/src/test/java/com/foundationdb/server/test/it/qp/IndexScanBoundedPKIT.java
fdb-sql-layer-core/src/test/resources/log4j.properties

Add a endExclusive flag for the end of range on a key selector. By setting this correctly the FDB K/V Store returns only exactly the rows required by the index scan. This is a performance enhancement (fewer rows from the storage layer). 
Add one new test to verify the variations on a test which was failing elsewhere. So make sure we catch all the variations as well, as a specific test. 
All of the tests have been run with the two asserts in `IndexCursorUnidirectional.java` enabled and they all pass (including the new one). But they need to be disabled in the production code because they won't pass with the Persistit storage layer enabled.

Key selector end exclusive flag

---

fdb-sql-layer-common/test/resources/tests.policy

IntelliJ, at least, is happy with this plus `-Dfdbsql.test.extra_policy_path="/Applications/IntelliJ IDEA 14 CE.app"` in the test config.

Add external config path in test policy

---

fdb-sql-layer-core/src/main/java/com/foundationdb/server/store/statistics/AbstractIndexStatisticsService.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/store/statistics/AbstractStoreIndexStatistics.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/store/statistics/FDBIndexStatisticsService.java
fdb-sql-layer-core/src/main/java/com/foundationdb/server/store/statistics/FDBStoreIndexStatistics.java

Thanks to the row cleanup the default format, or any really, can be used just fine.
Existing data sets are fine as the tables have always been serialized with the knowledge of their storage format.

FDB index stats does not require rowdata
